# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Postq < Formula
  desc "PostQ CLI — quantum-risk scanning for TLS, certs, and cloud crypto."
  homepage "https://postq.dev"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PostQDev/postq-cli/releases/download/v0.3.1/postq_0.3.1_darwin_amd64.tar.gz"
      sha256 "c70c2001519c59ce9184b7220703a7931fd70fd9325bc0a37dda1aac18279752"

      define_method(:install) do
        bin.install "postq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PostQDev/postq-cli/releases/download/v0.3.1/postq_0.3.1_darwin_arm64.tar.gz"
      sha256 "c56066fd0d8cf09a88e2913e097fee8509f21419c8ebe1e45abc7a76c8e9e878"

      define_method(:install) do
        bin.install "postq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PostQDev/postq-cli/releases/download/v0.3.1/postq_0.3.1_linux_amd64.tar.gz"
      sha256 "c59a9252b00fed9e4e492b850955f91cda4b471315ac209432dbc36c2da9a4f9"
      define_method(:install) do
        bin.install "postq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PostQDev/postq-cli/releases/download/v0.3.1/postq_0.3.1_linux_arm64.tar.gz"
      sha256 "efaa0fade7f5c057490b1af976c7825be66e6a6b43ae1b99b58f5e0450c0da03"
      define_method(:install) do
        bin.install "postq"
      end
    end
  end

  test do
    system "#{bin}/postq", "version"
  end
end
