# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Postq < Formula
  desc "PostQ CLI and MCP server for quantum-risk scanning and hybrid signing."
  homepage "https://postq.dev"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PostQDev/postq-cli/releases/download/v0.6.1/postq_0.6.1_darwin_amd64.tar.gz"
      sha256 "c35a6bae19a2d109e343d36aa4e696509936b5f54199c620cb183be18f1d668c"

      define_method(:install) do
        bin.install "postq"
        bin.install "postq-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PostQDev/postq-cli/releases/download/v0.6.1/postq_0.6.1_darwin_arm64.tar.gz"
      sha256 "22b8651e8e295fd47c7b21d57e5e669863d0ff36edde2fad883b48fab1e02184"

      define_method(:install) do
        bin.install "postq"
        bin.install "postq-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PostQDev/postq-cli/releases/download/v0.6.1/postq_0.6.1_linux_amd64.tar.gz"
      sha256 "4bb7fa6bee985aadecf6e441551ca2ce3c6cef217d7140e2053a4e4c0d2bffa7"
      define_method(:install) do
        bin.install "postq"
        bin.install "postq-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PostQDev/postq-cli/releases/download/v0.6.1/postq_0.6.1_linux_arm64.tar.gz"
      sha256 "1a164a0eca3f8b37d950dc078661d4fa73bda14a80c75f65a143b38b281939d7"
      define_method(:install) do
        bin.install "postq"
        bin.install "postq-mcp"
      end
    end
  end

  test do
    system "#{bin}/postq", "version"
    assert_match "postq-mcp", shell_output("#{bin}/postq-mcp </dev/null 2>&1")
  end
end
